### ISSUE TITLE
Boolean strings

### ISSUE THREAD

**Issue by sillvva** [fabian-hiller/decode-formdata#1]
One issue I ran into was that the decode function doesn't parse `"true"` or `"false"` strings to their corresponding boolean values. Both just result in `true`. To get `false`, you need to exclude the field from the form data altogether.

I think this could be an area for improvement.
- True: any value, except `"false"`, `"0"`
- False: `"false"`, `"0"`, excluded

**Comment by fabian-hiller** [comment]
Great idea. I will think about it. Feel free to create a PR if you have time.

**Comment by fabian-hiller** [comment]
Here is the code located: https://github.com/fabian-hiller/decode-formdata/blob/main/src/utils/getFieldValue/getFieldValue.ts#L19-L21

**Comment by fabian-hiller** [comment]
Maybe this is the solution:

```ts
if (info?.booleans?.includes(templateName)) {
  return value !== 'false' && value !== '0';
}
```

**Comment by sillvva** [comment]
I haven't taken the time to study the code yet, but that looks good to me.

**Comment by fabian-hiller** [comment]
Will add it later
