### ISSUE TITLE
decode() creates a way more array items than it should be

### ISSUE THREAD

**Issue by wiesson** [fabian-hiller/decode-formdata#12]
I'm not sure if it's a bug from `decode-formdata` or my application went rouge. I'm slowly replacing my custom logic with decode and valibot.

```Javascript
const formData = await request.formData();
const formValues = decode(formData, {
	arrays: ['itineraries'],
	numbers: ['itineraries.$.days_from', 'itineraries.$.days_to'],
	booleans: ['itineraries.$.deleted']
});
```

formValues.itineraries is an array with 21512 items. It should have 4 items. I'm not sure if it's a bug of svelte kit or sth else is not correct. I'm using the newest versions everywhere (node 20).

Maybe you have an idea, what it could be :)

![Screenshot 2024-05-16 at 14 02 24](https://github.com/fabian-hiller/decode-formdata/assets/933231/5cd9730e-42cb-4c4f-bd74-38ec8860a6a0)

![Screenshot 2024-05-16 at 14 10 12](https://github.com/fabian-hiller/decode-formdata/assets/933231/701230dd-de0a-4353-a4f5-c549c948964c)

**Comment by fabian-hiller** [comment]
Can you provide a minimal reproduction that I can use to write a unit test? Feel free to take a look at the current unit tests of `decode`: https://github.com/fabian-hiller/decode-formdata/blob/main/src/decode.test.ts

**Comment by fabian-hiller** [comment]
The library has 100% test coverage. Bugs are therefore unlikely, but still possible. I am happy to fix it if there are bugs related to your problem.

**Comment by wiesson** [comment]
I could not get it to those extreme values, but I might have found something:

```Typescript
  test('should transform nested values', () => {
    const formData = new FormData();

    formData.append(`nested.${1}.id`, '1');
    const formValues = decode(formData);
    expect(formValues).toEqual({
      nested: [{ id: '1' }],
    });
  });
  ```
  
Creates

```Typescript
{ nested: [ <1 empty item>, { id: '1' } ] }
```

The empty "delete" false should not be there.

**Comment by wiesson** [comment]
I think I misunderstood the usage of the nested objects. 

If I add sth like this:
```ts
test('should transform nested values', () => {
    const formData = new FormData();

    formData.append(`nested.23.id`, 'some-id');
    const formValues = decode(formData);
    console.log(formValues);
    expect(formValues).toEqual({
      nested: [{ id: 'some-id' }],
    });
  });
  ```
  
I get `{ nested: [ <23 empty items>, { id: 'some-id' } ] }`.. So it tries to add 23 items and extract the id field. I assumed, I could add any key in `nested.id.bar`. But the index should start at 0 (Obviously).

**Comment by wiesson** [comment]
I'll close it, but it took me a couple of hours to spot my issue 🙈

**Comment by fabian-hiller** [comment]
I think your problem is related to JavaScript in general and not to `decode`. This library does not add empty elements, it is JavaScript itself. See this example:

```js
const array = [];
array[2] = 2;
console.log(array); // [empty, empty, 2]
```

Feel free to contact me if you have any other questions about this library. I am happy to help.

**Comment by wiesson** [comment]
I just didn't think of it - I was so into, "I'll add the entity id here" instead of the "array index". Everything makes sense though.
