### ISSUE TITLE
The field in the format text[$].text is not decoded

### ISSUE THREAD

**Issue by nihilum-labs** [fabian-hiller/decode-formdata#14]
Hello, I'm trying to parse such a field:
```tsx
 <input
 type="hidden"
 defaultValue={element.baseCurrency.id}
 name={`exchangeRates[${i}].baseCurrency`}
 />
```
the result:
```ts
  const validatedFormData = decode(formData, {
    numbers: [
      'exchangeRates[$].baseCurrency',
      'exchangeRates[$].targetCurrency',
    ],
  });
```
I have already tried to arrange the parttern in different ways. But everything does not work out.
```ts
formData: FormData {
  [Symbol(state)]: [
    { name: 'exchangeRates[0].baseCurrency', value: '1' },
    { name: 'exchangeRates[0].targetCurrency', value: '2' },
    { name: 'exchangeRates[0].rate', value: '8.5500' },
    { name: 'exchangeRates[1].baseCurrency', value: '2' },
    { name: 'exchangeRates[1].targetCurrency', value: '1' },
    { name: 'exchangeRates[1].rate', value: '10.0000' }
  ]
}
```
```ts
validatedFormData: {
  'exchangeRates[0]': { baseCurrency: '1', targetCurrency: '2', rate: '8.5500' },
  'exchangeRates[1]': { baseCurrency: '2', targetCurrency: '1', rate: '10.0000' }
}
```
I must be doing something wrong. Can you tell me?

**Comment by fabian-hiller** [comment]
I think that we do not support this format. Can you change the field name to a dot path? So instead of `exchangeRates[${i}].baseCurrency` write `exchangeRates.${i}.baseCurrency`.

```tsx
 <input
   type="hidden"
   defaultValue={element.baseCurrency.id}
   name={`exchangeRates[${i}].baseCurrency`}
 />
 ```
 
 ```ts
const validatedFormData = decode(formData, {
  numbers: ['exchangeRates.$.baseCurrency', 'exchangeRates.$.targetCurrency'],
});
 ```

**Comment by nihilum-labs** [comment]
This record format comes from [TanStack Form](https://github.com/TanStack/form). Only this format allow exchangeRates[${number}].baseCurrency
I will try to ask developers @tannerlinsley & @crutchcorn if it is possible to change the type somehow. I learned about your library from @crutchcorn

**Comment by nihilum-labs** [comment]
Devs replied that the format cannot be changed. Is it possible in decode to make a pattern selection for such cases?
May be feature for future.

**Comment by fabian-hiller** [comment]
I think I should talk to @crutchcorn. If they are using this library without following its format, something is wrong. I am open to discussion to support both formats.

**Comment by crutchcorn** [comment]
Deffo open to chat and even contribute to this library :)

**Comment by fabian-hiller** [comment]
I think it is possible to support both formats. Probably two changes are needed.

We need to support the `foo[123].bar` format when creating the template name and keys of a path: https://github.com/fabian-hiller/decode-formdata/blob/main/src/decode.ts#L51-L55

And we need to check the implementation everywhere `.arrays` is written in the [`decode`](https://github.com/fabian-hiller/decode-formdata/blob/main/src/decode.ts) source code. The library should be fully tested, so its hard to introduce bugs. Feel free to ccreate a PR.

**Comment by fabian-hiller** [comment]
v0.8.0 is available

**Comment by Balastrong** [comment]
That was fast, thank you!
