### ISSUE TITLE
Empty dates

### ISSUE THREAD

**Issue by sillvva** [fabian-hiller/decode-formdata#3]
Found one more issue related to dates. If a user leaves a date field empty, it returns as `""` and the decode function will return `Invalid Date`. This will cause a schema to fail, even if it accepts empty dates.

I currently handle it like this:

```ts
const formValues = decode(formData, {
	...info,
	dates: info?.dates?.filter((d) => formData.get(d)) // filter empty strings
});
```

This ensures they show up as `""` after decoding.

**Comment by fabian-hiller** [comment]
What is the expected behavior in this case? Should `undefined` be returned then?

**Comment by sillvva** [comment]
I think the expected behavior is that it returns either `""` or `null`.

`undefined` would be confusing, because the field exists so its value _is_ defined in FormData. It's just an empty value.

**Comment by fabian-hiller** [comment]
I am not sure. String is not an option as it is a completely different data type and also causes problems when using a schema library. Personally, I would expect `Invalid Date` or `undefined`, as I feel that `undefined` is the default behavior of JavaScript when something is missing. `null`, on the other hand, is a deliberate declaration of a missing value.

**Comment by sillvva** [comment]
If a person is using a schema validation library to validate a date, but also accepts empty dates, they should account for that in their schema. With Valibot, for example, if I just used `date()`, it's saying I expect a date and it must be filled.

If I wanted to accept an empty date, on the other hand, I would have to write it like this:

```ts
const nullableDateSchema = union([literal(""), date([custom((input) => !isNaN(input.getTime()), "Invalid Date")])]);
// or
const nullableDateSchema = nullable(date([custom((input) => !isNaN(input.getTime()), "Invalid Date")]));
```

This is saying: if a date is provided, it must be valid. If it's not provided, I expect `null` or `""`.

On one of my forms, I have a Date field which is required, and an Applied Date field which is optional as I expect it to be filled at some future date. In my database and schema, the type is `Date | null`.

To expand further, `undefined` is not a valid database value. `null` is.

**Comment by fabian-hiller** [comment]
I understand that, but it depends on the database. I think that an empty sting is the worst option. So I think the final decision will be between `undefined` or `null`. Alternatively, we could also make it configurable.

**Comment by fabian-hiller** [comment]
For the future, I thought about adding the possibility to dynamically transform the decoding of a value via a function. Below is an example that transforms an `undefined` date to `null`:

```ts
import { decode } from 'decode-formdata';

async function server(formData: FormData) {
  const formValues = decode(
    formData,
    { dates: ['created_at'] },
    (value, { path, type }) => {
      if (type === 'date' && !value) {
        return null;
      }
      return value;
    }
  );
}
```

**Comment by sillvva** [comment]
I would also be fine with a function. 😀 Otherwise, without that, I could still handle it with the schema.

```ts
export const nullableDateSchema = transform(
	nullish(date([custom((input) => !isNaN(input.getTime()), "Invalid Date")])),
	(input) => input || null
);
```

Ultimately, I think my main goal is to at least not have `InvalidDate` for empty date inputs. Otherwise, I can't tell an actual invalid date apart from an allowed empty input.

**Comment by fabian-hiller** [comment]
I thought about it again and did some research. `<input type="date" />` returns `null` if there is no input and `element.valueAsDate` is accessed. So I changed my mind and agree with your suggestion to change `Invalid Date` to `null`.
