### ISSUE TITLE
Cannot decode date if timestamp is a string

### ISSUE THREAD

**Issue by sacrosanctic** [fabian-hiller/decode-formdata#6]
Formdata content is always stored as a string. So if I am sending a [Timestamp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) to the server it will be converted to a string and fail.

# Repro
```js
const formData = new FormData()
formData.append('createdDate', new Date().getTime())
const data = decode(formData, { dates:['createdDate'] })
console.log(data)
```
[Demo](https://stackblitz.com/edit/stackblitz-starters-fbvxy7?file=index.js)

# Expected
```js
{
  createdDate: 2020-02-20T00:00:00.000Z
}
```
# Actual 
```js
{
  createdDate: Invalid Date
}
```
# Suggestion
- Parse the string timestamp
- provide documentation on what the decoder should expect for date input
- provide best practice on what to store the date as on the browser

# Addtional Info
btw, your package is awesome.

**Comment by fabian-hiller** [comment]
Just remove `createdDate` from `dates` if you want the value as a string instead of a date.

**Comment by fabian-hiller** [comment]
Or do you want a `Date` object and the problem is `Invalid Date`?

**Comment by sacrosanctic** [comment]
I want a date object

**Comment by fabian-hiller** [comment]
Have you tried to remove `.getTime()`?

**Comment by sacrosanctic** [comment]
The code above is demonstrating a scenario where the incoming date is a Timestamp.

Since `new Date(new Date().getTime())` will work.

Is parsing Timestamp as date outside the scope of this package?

**Comment by fabian-hiller** [comment]
Isn't `Date` converted to a string when send to the server via `FormData`? What should work is `new Date().toISOString()`.

**Comment by sacrosanctic** [comment]
This was the solution is found for myself as well, I just thought maybe the case where a user uses `.getTime()` should be handled for better DX.

**Comment by fabian-hiller** [comment]
Yes, we can add this use case. Do you want to create a PR or should I take care of it? That's the file: https://github.com/fabian-hiller/decode-formdata/blob/main/src/utils/getFieldDate/getFieldDate.ts

**Comment by sacrosanctic** [comment]
I can do it.
